config/routes.rb
Rails.application.routes.draw do
  resources :bookmarks
  root 'bookmarks#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    validates :title, :url, :interest, presence: true #タイトル、URL、面白さが空でないか？
    validates :url, format: /\A#{URI::regexp(%w(http https))}\z/ #urlか？
    validates :title, uniqueness: true, length: {maximum: 50} #タイトルはユニークか？文字数は50以下か？
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.all
  end
  
  def new
    @bookmark = Bookmark.new
  end
  
  def create
    @bookmark = Bookmark.new(title: params[:bookmark][:title], url: params[:bookmark][:url], interest: params[:bookmark][:interest])
    if @bookmark.save
      flash[:notice] = '1レコード追加しました'
      redirect_to '/'
    else
      render 'new', status: :unprocessable_entity
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    flash[:notice] = '1レコード削除しました'
    redirect_to '/'
  end
  
  def show
    @bookmark = Bookmark.find(params[:id])
  end
  
  def edit
    @bookmark = Bookmark.find(params[:id])
  end
  
  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(title: params[:bookmark][:title], url: params[:bookmark][:url], interest: params[:bookmark][:interest])
      flash[:notice] = '更新しました'
      redirect_to '/'
    else
      render 'edit', status: :unprocessable_entity
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/views/bookmarks/_form.html.erb
<div class="errors_message">
  <% if bookmark.errors.present? %>
    <h3>エラーがあります。</h3>
    <ul>
      <% bookmark.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="container_new">
  <%= form_with model: bookmark do |f| %>
    <div class="bookmark_new_info">
      <h1><%= f.label :title, 'タイトル' %></h1>
      <div class="info_item"><%= f.text_field :title %></div>

      <h1><%= f.label :url, 'URL' %></h1>
      <div class="info_item"><%= f.text_field :url %></div>

      <h1><%= f.label :interest, '面白さ' %></h1>
      <div class="info_item"><%= f.text_field :interest %></div>
    </div>

    <div class="submit_botan">
      <%= f.submit (bookmark.new_record? ? '登録' : '更新') %>
    </div>
  <% end %>

  <div class="back_botan">
    <%= link_to '戻る', root_path %>
  </div>
</div>

app/views/bookmarks/edit.html.erb
<div class="center_h2">
  <h2>ブックマーク編集</h2>
</div>
<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/index.html.erb
<div class="container_root">
  
  <% if flash[:notice] %>
    <div class="index_flash">
      <%= flash[:notice] %>
    </div>
  <% end %>
  
  <% if @bookmarks.empty? %>
    <div class="no_bookmarks">
      <p>まだブックマークが何もありません</p>
      <p><%= link_to '新しく追加してみよう！', new_bookmark_path, class: "add_link" %></p>
    </div>
  <% else %>
    <% @bookmarks.each do |book| %>
      <div class="bookmark_info">
        <h1><%= link_to book.title, book.url %></h1>
        <p>面白さ：<%= book.interest %></p>
        <%= link_to '表示', bookmark_path(book) %>
        <%= link_to '編集', edit_bookmark_path(book) %>
        <div class="delete_botan"><%= link_to '削除', bookmark_path(book), data: {turbo_method: :delete} %></div>
      </div>
    <% end %>
  <% end %>
  
</div>

app/views/bookmarks/new.html.erb
<div class="center_h2">
  <h2>新規ブックマーク登録</h2>
</div>

<%= render "form", bookmark: @bookmark %>

app/views/bookmarks/show.html.erb
<div class="container">
  <div class="bookmark_info">
    <div class="font_big">
      <p>
        <strong>タイトル：</strong>
        <%= @bookmark.title %>
      </p>
      
      <p>
        <strong>URL：</strong>
        <%= @bookmark.url %>
      </p>
      
      <p>
        <strong>面白さ：</strong>
        <%= @bookmark.interest %>
      </p>
    </div>
    
    <div class="back_botan">
      <%= link_to '戻る', root_path %>
    </div>
    
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
    <p>&copy; 2025 BookmarkApp</p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <div class="header_content">
        <div class="app_title">
            <h1>BookmarkApp</h1>
        </div>
    </div>
</header>

app/views/layouts/_sidebar.html.erb
<%= link_to "+新規追加", new_bookmark_path %>
<br>
<%= link_to "ブックマーク一覧", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp1" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      
      <%= render "layouts/header" %>
      
      <div class="main-content">
        <div class="content">
          <%= yield %>
        </div>
        
        <div class="sidebar">
          <%= render "layouts/sidebar" %>
        </div>
        
      </div>
      
      <%= render "layouts/footer" %>
      
    </div>
    
  </body>
</html>